import ccxt
import pandas as pd
import numpy as np
import time

# The assets parsed from your image
ASSETS = [
    'BTC/USD', 'SNX/USD', 'DASH/USD', 'MORPHO/USD',
    'EC/USD', 'ZRO/USD', 'SAPIEN/USD', 'TRUMP/USD',
    'MIR/USD', 'AB/USD', 'BCH/USD', 'SOL/USD'
]

def fetch_ohlcv_data(exchange, symbol, timeframe='1d', limit=365):
    """
    Fetches historical OHLCV data from the specified exchange.
    Returns a Pandas DataFrame or None if the symbol isn't supported.
    """
    try:
        # ccxt handles rate limiting automatically if enabled, but a small sleep never hurts
        time.sleep(exchange.rateLimit / 1000) 
        
        ohlcv = exchange.fetch_ohlcv(symbol, timeframe, limit=limit)
        
        if not ohlcv:
            return None
            
        df = pd.DataFrame(ohlcv, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
        df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')
        df.set_index('timestamp', inplace=True)
        
        return df
        
    except ccxt.BadSymbol:
        # Fails silently for unsupported pairs so the script doesn't crash
        return None
    except Exception as e:
        print(f"Network or API error fetching {symbol}: {e}")
        return None

def backtest_sma_crossover(data, short_window=20, long_window=50):
    """
    Executes a standard SMA Crossover strategy on the provided DataFrame.
    """
    df = data.copy()
    
    # Calculate moving averages
    df['SMA_Short'] = df['close'].rolling(window=short_window, min_periods=1).mean()
    df['SMA_Long'] = df['close'].rolling(window=long_window, min_periods=1).mean()
    
    # Generate trading signals (1.0 = Buy/Hold, 0.0 = Sell/Flat)
    df['Signal'] = 0.0
    df['Signal'] = np.where(df['SMA_Short'] > df['SMA_Long'], 1.0, 0.0)
    
    # Calculate daily returns based on the 'close' price
    df['Market_Return'] = df['close'].pct_change()
    
    # Strategy returns (shifted by 1 to prevent look-ahead bias)
    df['Strategy_Return'] = df['Market_Return'] * df['Signal'].shift(1)
    
    # Drop NaNs generated by pct_change and rolling windows
    df.dropna(inplace=True)
    
    # Calculate cumulative performance
    if len(df) > 0:
        cumulative_market = (1 + df['Market_Return']).cumprod() - 1
        cumulative_strategy = (1 + df['Strategy_Return']).cumprod() - 1
        return cumulative_market.iloc[-1], cumulative_strategy.iloc[-1]
    else:
        return 0.0, 0.0

def run_real_data_paper_test():
    """
    Connects to the exchange, fetches data, and runs the backtest across all assets.
    """
    # Initialize exchange. 
    # Swap 'kraken' to 'binanceus' or 'cryptocom' depending on where your API keys live,
    # but be prepared to change /USD to /USDT if the exchange dropped fiat pairs.
    exchange = ccxt.kraken({'enableRateLimit': True})
    
    print(f"Connecting to {exchange.id} to fetch historical data...")
    print("Starting Paper Test: SMA Crossover Strategy (20-day vs 50-day)")
    print("-" * 75)
    print(f"{'Ticker':<15} | {'Status':<15} | {'Market Return':<15} | {'Strategy Return'}")
    print("-" * 75)
    
    for asset in ASSETS:
        # Fetch up to 1 year of daily data
        data = fetch_ohlcv_data(exchange, asset, timeframe='1d', limit=365)
        
        if data is None or data.empty:
            print(f"{asset:<15} | {'UNSUPPORTED':<15} | {'N/A':<15} | N/A")
            continue
            
        market_ret, strat_ret = backtest_sma_crossover(data)
        print(f"{asset:<15} | {'SUCCESS':<15} | {market_ret:>14.2%} | {strat_ret:>14.2%}")

if __name__ == "__main__":
    # Ensure you have the required libraries installed:
    # pip install ccxt pandas numpy
    run_real_data_paper_test()
